server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gokulr488/cloudconfig.git
          default-label: master
          username: gokulr488
          password: ${GITHUB_TOKEN}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true