server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: true
spring:
  application:
    name: discovery-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: payments
            uri: lb://payments-service/payments
            predicates:
              - Path=/payments/**
          - id: buyermgt
            uri: lb://buyermgt/buyermgt
            predicates:
              - Path=/buyermgt/**