server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: discovery-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: payments
            uri: lb://payments-service
            predicates:
              - Path=/payments/**